version: "3"

services:
  wolf:
    image: ghcr.io/games-on-whales/wolf:stable
    restart: unless-stopped

    ports:
      - '47984:47984' # HTTPS
      - '47989:47989' # HTTP
      - '47999:47999/udp' # Control
      - '48010:48010' # RTSP
      - '48100:48100/udp' # Video
      - '48200:48200/udp' # Audio

    volumes:
      - /etc/wolf/:/etc/wolf
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev/:/dev/:rw
      - /run/udev:/run/udev:rw

    environment:
      - TZ=Europe/Amsterdam

    device_cgroup_rules:
      - 'c 13:* rmw'
    devices:
      - /dev/dri
      - /dev/uinput
      - /dev/uhid

networks:
  default:
    external: true
    name: nginx
